# Generated by Django 5.2.16 on 2026-07-11 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_moderationreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='story',
            field=models.TextField(blank=True, help_text='Un breve racconto sul brano, mostrato nella sua pagina.'),
        ),
    ]
