# Generated by Django 5.2.16 on 2026-07-11 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_playlist_collaborators_song_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='pending_collaborators',
            field=models.ManyToManyField(blank=True, related_name='playlist_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
