# Generated by Django 5.2.16 on 2026-07-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_role_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('listener', 'Listener'), ('curator', 'Curator'), ('moderator', 'Moderator')], default='listener', max_length=20),
        ),
    ]
