# Generated by Django 5.2.16 on 2026-07-11 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_bio_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_image',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
